// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/mysql/employment/repository.go

// Package mockemployment is a generated GoMock package.
package mockemployment

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entity "github.com/ramasuryananda/dummy-cv/internal/dto/entity"
)

// MockRepositoryProvider is a mock of RepositoryProvider interface.
type MockRepositoryProvider struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryProviderMockRecorder
}

// MockRepositoryProviderMockRecorder is the mock recorder for MockRepositoryProvider.
type MockRepositoryProviderMockRecorder struct {
	mock *MockRepositoryProvider
}

// NewMockRepositoryProvider creates a new mock instance.
func NewMockRepositoryProvider(ctrl *gomock.Controller) *MockRepositoryProvider {
	mock := &MockRepositoryProvider{ctrl: ctrl}
	mock.recorder = &MockRepositoryProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepositoryProvider) EXPECT() *MockRepositoryProviderMockRecorder {
	return m.recorder
}

// CreateEmploymentData mocks base method.
func (m *MockRepositoryProvider) CreateEmploymentData(ctx context.Context, data entity.Employment) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEmploymentData", ctx, data)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateEmploymentData indicates an expected call of CreateEmploymentData.
func (mr *MockRepositoryProviderMockRecorder) CreateEmploymentData(ctx, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEmploymentData", reflect.TypeOf((*MockRepositoryProvider)(nil).CreateEmploymentData), ctx, data)
}

// DeleteEmploymentData mocks base method.
func (m *MockRepositoryProvider) DeleteEmploymentData(ctx context.Context, profileCode, id uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteEmploymentData", ctx, profileCode, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteEmploymentData indicates an expected call of DeleteEmploymentData.
func (mr *MockRepositoryProviderMockRecorder) DeleteEmploymentData(ctx, profileCode, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEmploymentData", reflect.TypeOf((*MockRepositoryProvider)(nil).DeleteEmploymentData), ctx, profileCode, id)
}

// GetEmploymentByProfileCode mocks base method.
func (m *MockRepositoryProvider) GetEmploymentByProfileCode(ctx context.Context, profileCode uint64) ([]entity.Employment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmploymentByProfileCode", ctx, profileCode)
	ret0, _ := ret[0].([]entity.Employment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEmploymentByProfileCode indicates an expected call of GetEmploymentByProfileCode.
func (mr *MockRepositoryProviderMockRecorder) GetEmploymentByProfileCode(ctx, profileCode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmploymentByProfileCode", reflect.TypeOf((*MockRepositoryProvider)(nil).GetEmploymentByProfileCode), ctx, profileCode)
}

// GetFirstEmploymentByProfileCodeandID mocks base method.
func (m *MockRepositoryProvider) GetFirstEmploymentByProfileCodeandID(ctx context.Context, profileCode, id uint64) (entity.Employment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFirstEmploymentByProfileCodeandID", ctx, profileCode, id)
	ret0, _ := ret[0].(entity.Employment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFirstEmploymentByProfileCodeandID indicates an expected call of GetFirstEmploymentByProfileCodeandID.
func (mr *MockRepositoryProviderMockRecorder) GetFirstEmploymentByProfileCodeandID(ctx, profileCode, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFirstEmploymentByProfileCodeandID", reflect.TypeOf((*MockRepositoryProvider)(nil).GetFirstEmploymentByProfileCodeandID), ctx, profileCode, id)
}
